name: "Integration Tests"

on:
  pull_request:
    branches:
      - main
    path:
      - modules/**
      - flake.nix
      - flake.lock
      - .github/workflows/create-test-plan.sh
      - .github/workflows/integration-tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-test-plan:
    name: Create test plan

    runs-on: ubuntu-latest
    outputs:
      checks: ${{ steps.get-changed-checks.outputs.checks }}
      run-all-checks: ${{ steps.get-changed-checks.outputs.run-all-checks }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0 # Need the entire history to properly calculate the diff
      - uses: DeterminateSystems/nix-installer-action@v17
      - name: Get changed checks
        id: get-changed-checks
        run: ./.github/workflows/create-test-plan.sh

  run-checks:
    name: Run select checks
    runs-on: ubuntu-latest
    needs: create-test-plan
    if: ${{ needs.create-test-plan.outputs.run-all-checks == 'false' && needs.create-test-plan.outputs.checks != '[]' && needs.create-test-plan.outputs.checks != '' }}
    strategy:
      matrix:
        check: ${{ fromJSON(needs.create-test-plan.outputs.checks) }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: DeterminateSystems/nix-installer-action@v17
      - run: |
          nix run .#checks.x86_64-linux.${{ matrix.check }}.driver

  integration-tests:
    name: Run all checks
    runs-on: ubuntu-latest
    needs: create-test-plan
    if: ${{ needs.create-test-plan.outputs.run-all-checks == 'true' }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: DeterminateSystems/nix-installer-action@v17
      - run: |
          nix flake check

  result:
    name: Verify test results
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [integration-tests, run-checks]
    steps:
      - run: |
          if [ "${{ needs.integration-tests.result }}" = "failure" ] || [ "${{ needs.run-checks.result }}" = "failure" ]; then
            echo Previous step failed, blocking PR.
            exit 1;
          fi

          if [ "${{ needs.integration-tests.result }}" = "success" ] || [ "${{ needs.run-checks.result }}" = "success" ]; then
            echo Previous step succeeded, PR is good to go.
            exit 0;
          fi

          if [ "${{ needs.integration-tests.result }}" = "skipped" ] && [ "${{ needs.run-checks.result }}" = "skipped" ]; then
            echo No check needed, PR is good to go.
            exit 0;
          fi

          exit 1;
